name: voprf
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.8.2
  convert: ^3.1.2
  crypto: ^3.0.7
  ristretto255: ^1.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
